export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export const SEARCH_POKEMON_ERROR = 'SEARCH_POKEMON_ERROR';
